### PR TITLE
lazy loading of images

### PR DESCRIPTION
**Pull request by tfriedel**
use LazyLoadDict and shelve for detections to reduce memory consumption
supposed to go with https://github.com/roboflow/supervision/pull/353

### CODE REVIEW

**Comment by tfriedel** [comment]
this may need other changes, like the dependencies would need to be updated to get the new supervision lib

**Comment by AlainPilon** [comment]
👀

**Review by capjamesg — CHANGES_REQUESTED** [review]
@tfriedel Can you add the requisite dependency change to the `requirements.txt` when this feature is available in supervision? Aside from that, this looks good to me.

**Comment by tfriedel** [comment]
@capjamesg sure, just ping me here when this happens

**Comment by capjamesg** [comment]
@tfriedel Is the lazy loading API likely to be in the next release?

**Comment by tfriedel** [comment]
@capjamesg no idea, I'm just an external contributor. If I get notified that the other PR is merged we can continue here.

**Comment by AChangXD** [comment]
@capjamesg Running into this issue as well, any idea on when this can be merged?

**Comment by KTXKIKI** [comment]
How is the situation

**Comment by capjamesg** [comment]
@tfriedel Now that supervision supports the shelf functionality, are we ready to continue with this PR?

**Comment by tfriedel** [comment]
@capjamesg sorry, this is too long ago now. I'm not using the library and have no interest in continuing to work on it at this time. But feel free to continue the work and make a new PR for example.

**Pull request closed without merging**
