### PR TITLE
feat: fixing issue#53

### LINKED ISSUE #53: TypeError: expected str, bytes or os.PathLike object, not ClassificationDataset
When I use autodistill-clip for image classification, the runtime prompts this error:TypeError: expected str, bytes or os.PathLike object, not ClassificationDataset
image

### PR DESCRIPTION
**Pull request by muhammad-usama-aleem**
### Description

This PR resolves issue #53, which was causing a `TypeError` related to the use of `ClassificationDataset`. This bug appeared because the detection and classification were using the same `split_data` function.

### Changes Made

- created a new function named `split_data_classification` in the helpers.py 
- called the above mentioned function in the `classification_base_model.py` for splitting the dataset.

### Testing

I have thoroughly tested these changes on my local environment using roboflow dataset. All tests pass successfully, and the issue seems to be resolved.

### Screenshots

Before:

before

### Checklist

- [x] The code follows the project's coding standards.
- [x] Tests have been added or updated to cover the changes.
- [x] Documentation has been updated, if necessary.

### Related Issues

Closes #53

### Reviewer Guidance

[Provide any specific guidance for reviewers, such as areas to pay attention to or specific test cases to check.]

### CODE REVIEW

**Comment by muhammad-usama-aleem** [comment]
@yeldarby Can you please review my PR? It's my first time contributing to the open source, so would really appreciate some feedback in case I am doing something wrong.

**Comment by muhammad-usama-aleem** [comment]
In this Commit, I am now using `split` function from supervision as you suggested. I have also removed the function which I created to split the dataset.

**Comment by muhammad-usama-aleem** [comment]
@capjamesg can you please review my PR?

**Comment by capjamesg** [comment]
@muhammad-usama-aleem There is one comment for you to review.

**Comment by muhammad-usama-aleem** [comment]
> Hello there! Thank you for your contribution! When we implemented Autodistill, supervision, which we use to manage predictions and datasets, didn't have a final data splitting API. Now, that API is available.
> 
> You can split classification datasets using supervision like this: https://supervision.roboflow.com/datasets/#supervision.dataset.core.ClassificationDataset.split
> 
> Would you be able to update your PR to use the split() API documented in the link above?
> 
> Once we use that API, I'll do a test and make sure everything works as expected. If it does, we can merge your contribution!

Thank you for your response.
If you are talking about the above comment, then my `feat: using split function from supervision to split dataset` commit resolved that.

If you are talking about something else then please let me know.

**Comment by capjamesg** [comment]
@muhammad-usama-aleem Please see https://github.com/autodistill/autodistill/pull/100/files/7adb8562a25513a8b42a1fd17176dfe2af884081#diff-a6570d85123e7de60b1f1a7d702b43f7b6c236f805287e4c0c88ff9ac24086b5.

**Comment by muhammad-usama-aleem** [comment]
> @muhammad-usama-aleem Please see https://github.com/autodistill/autodistill/pull/100/files/7adb8562a25513a8b42a1fd17176dfe2af884081#diff-a6570d85123e7de60b1f1a7d702b43f7b6c236f805287e4c0c88ff9ac24086b5.

oh you mean the unused imports which I made. Removing them.

**Review by capjamesg — APPROVED** [review]
I have changed the `train_cs.split` to `test_cs.split`. This is because we want to make the test and valid sets using images that are _not_ in the test set.

**Pull request merged**
